"""add sended by to message

Revision ID: dce495e3513b
Revises: ea9145f4ce92
Create Date: 2025-04-01 20:37:37.551963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce495e3513b'
down_revision: Union[str, None] = 'ea9145f4ce92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('sended_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chat_messages', 'users', ['sended_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'sended_by')
    # ### end Alembic commands ###
